

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Shreyas
 */
public class S3 extends javax.swing.JFrame {

    /**
     * Creates new form S3
     */
    public S3() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jTextField4 = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jTextField5 = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jTextField6 = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jTextField7 = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        jTextField8 = new javax.swing.JTextField();
        jPanel9 = new javax.swing.JPanel();
        jTextField9 = new javax.swing.JTextField();
        jPanel10 = new javax.swing.JPanel();
        jTextField10 = new javax.swing.JTextField();
        jPanel11 = new javax.swing.JPanel();
        jTextField11 = new javax.swing.JTextField();
        jPanel12 = new javax.swing.JPanel();
        jTextField12 = new javax.swing.JTextField();
        jPanel13 = new javax.swing.JPanel();
        jTextField13 = new javax.swing.JTextField();
        jPanel14 = new javax.swing.JPanel();
        jTextField2 = new javax.swing.JTextField();
        jPanel15 = new javax.swing.JPanel();
        jTextField3 = new javax.swing.JTextField();
        jPanel16 = new javax.swing.JPanel();
        jTextField14 = new javax.swing.JTextField();
        jPanel17 = new javax.swing.JPanel();
        jTextField15 = new javax.swing.JTextField();
        jPanel18 = new javax.swing.JPanel();
        jTextField16 = new javax.swing.JTextField();
        jPanel19 = new javax.swing.JPanel();
        jTextField17 = new javax.swing.JTextField();
        jPanel20 = new javax.swing.JPanel();
        jTextField18 = new javax.swing.JTextField();
        jPanel21 = new javax.swing.JPanel();
        jTextField19 = new javax.swing.JTextField();
        jPanel22 = new javax.swing.JPanel();
        jTextField20 = new javax.swing.JTextField();
        jPanel23 = new javax.swing.JPanel();
        jTextField21 = new javax.swing.JTextField();
        jPanel24 = new javax.swing.JPanel();
        jTextField22 = new javax.swing.JTextField();
        jPanel25 = new javax.swing.JPanel();
        jTextField23 = new javax.swing.JTextField();
        jPanel26 = new javax.swing.JPanel();
        jTextField24 = new javax.swing.JTextField();
        jPanel27 = new javax.swing.JPanel();
        jTextField25 = new javax.swing.JTextField();
        jPanel28 = new javax.swing.JPanel();
        jTextField26 = new javax.swing.JTextField();
        jPanel29 = new javax.swing.JPanel();
        jTextField27 = new javax.swing.JTextField();
        jPanel30 = new javax.swing.JPanel();
        jTextField36 = new javax.swing.JTextField();
        jPanel31 = new javax.swing.JPanel();
        jTextField28 = new javax.swing.JTextField();
        jPanel32 = new javax.swing.JPanel();
        jTextField29 = new javax.swing.JTextField();
        jPanel33 = new javax.swing.JPanel();
        jTextField30 = new javax.swing.JTextField();
        jPanel34 = new javax.swing.JPanel();
        jTextField31 = new javax.swing.JTextField();
        jPanel35 = new javax.swing.JPanel();
        jTextField32 = new javax.swing.JTextField();
        jPanel36 = new javax.swing.JPanel();
        jTextField33 = new javax.swing.JTextField();
        jPanel37 = new javax.swing.JPanel();
        jTextField34 = new javax.swing.JTextField();
        jPanel38 = new javax.swing.JPanel();
        jTextField35 = new javax.swing.JTextField();
        jPanel39 = new javax.swing.JPanel();
        jTextField37 = new javax.swing.JTextField();
        jPanel40 = new javax.swing.JPanel();
        jTextField38 = new javax.swing.JTextField();
        jPanel41 = new javax.swing.JPanel();
        jTextField39 = new javax.swing.JTextField();
        jPanel42 = new javax.swing.JPanel();
        jTextField40 = new javax.swing.JTextField();
        jPanel43 = new javax.swing.JPanel();
        jTextField41 = new javax.swing.JTextField();
        jPanel44 = new javax.swing.JPanel();
        jTextField42 = new javax.swing.JTextField();
        jPanel45 = new javax.swing.JPanel();
        jTextField43 = new javax.swing.JTextField();
        jPanel46 = new javax.swing.JPanel();
        jTextField44 = new javax.swing.JTextField();
        jPanel47 = new javax.swing.JPanel();
        jTextField45 = new javax.swing.JTextField();
        jPanel48 = new javax.swing.JPanel();
        jTextField46 = new javax.swing.JTextField();
        jPanel49 = new javax.swing.JPanel();
        jTextField47 = new javax.swing.JTextField();
        jPanel50 = new javax.swing.JPanel();
        jTextField48 = new javax.swing.JTextField();
        jPanel51 = new javax.swing.JPanel();
        jTextField49 = new javax.swing.JTextField();
        jPanel52 = new javax.swing.JPanel();
        jTextField50 = new javax.swing.JTextField();
        jPanel53 = new javax.swing.JPanel();
        jTextField51 = new javax.swing.JTextField();
        jPanel54 = new javax.swing.JPanel();
        jTextField54 = new javax.swing.JTextField();
        jPanel55 = new javax.swing.JPanel();
        jTextField52 = new javax.swing.JTextField();
        jPanel56 = new javax.swing.JPanel();
        jTextField53 = new javax.swing.JTextField();
        jPanel57 = new javax.swing.JPanel();
        jTextField55 = new javax.swing.JTextField();
        jPanel58 = new javax.swing.JPanel();
        jTextField56 = new javax.swing.JTextField();
        jPanel59 = new javax.swing.JPanel();
        jTextField57 = new javax.swing.JTextField();
        jPanel60 = new javax.swing.JPanel();
        jTextField58 = new javax.swing.JTextField();
        jPanel61 = new javax.swing.JPanel();
        jTextField59 = new javax.swing.JTextField();
        jPanel62 = new javax.swing.JPanel();
        jTextField60 = new javax.swing.JTextField();
        jPanel63 = new javax.swing.JPanel();
        jTextField61 = new javax.swing.JTextField();
        jPanel64 = new javax.swing.JPanel();
        jTextField62 = new javax.swing.JTextField();
        jPanel65 = new javax.swing.JPanel();
        jTextField63 = new javax.swing.JTextField();
        jPanel66 = new javax.swing.JPanel();
        jTextField64 = new javax.swing.JTextField();
        jPanel67 = new javax.swing.JPanel();
        jTextField65 = new javax.swing.JTextField();
        jPanel68 = new javax.swing.JPanel();
        jTextField66 = new javax.swing.JTextField();
        jPanel69 = new javax.swing.JPanel();
        jTextField67 = new javax.swing.JTextField();
        jPanel70 = new javax.swing.JPanel();
        jTextField68 = new javax.swing.JTextField();
        jPanel71 = new javax.swing.JPanel();
        jTextField69 = new javax.swing.JTextField();
        jPanel72 = new javax.swing.JPanel();
        jTextField70 = new javax.swing.JTextField();
        jPanel73 = new javax.swing.JPanel();
        jTextField71 = new javax.swing.JTextField();
        jPanel74 = new javax.swing.JPanel();
        jTextField72 = new javax.swing.JTextField();
        jPanel75 = new javax.swing.JPanel();
        jTextField73 = new javax.swing.JTextField();
        jPanel76 = new javax.swing.JPanel();
        jTextField74 = new javax.swing.JTextField();
        jPanel77 = new javax.swing.JPanel();
        jTextField75 = new javax.swing.JTextField();
        jPanel78 = new javax.swing.JPanel();
        jTextField76 = new javax.swing.JTextField();
        jPanel79 = new javax.swing.JPanel();
        jTextField77 = new javax.swing.JTextField();
        jPanel80 = new javax.swing.JPanel();
        jTextField78 = new javax.swing.JTextField();
        jPanel81 = new javax.swing.JPanel();
        jTextField79 = new javax.swing.JTextField();
        jPanel82 = new javax.swing.JPanel();
        jTextField80 = new javax.swing.JTextField();
        jPanel83 = new javax.swing.JPanel();
        jTextField81 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jTextField82 = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.GridLayout(9, 9, 1, 1));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.setLayout(new java.awt.BorderLayout());

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel3.add(jTextField1, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel3);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel4.setLayout(new java.awt.BorderLayout());
        jPanel4.add(jTextField4, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel4);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel5.setLayout(new java.awt.BorderLayout());
        jPanel5.add(jTextField5, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel5);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel6.setLayout(new java.awt.BorderLayout());
        jPanel6.add(jTextField6, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel6);

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel7.setLayout(new java.awt.BorderLayout());
        jPanel7.add(jTextField7, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel7);

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel8.setLayout(new java.awt.BorderLayout());

        jTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8ActionPerformed(evt);
            }
        });
        jPanel8.add(jTextField8, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel8);

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel9.setLayout(new java.awt.BorderLayout());

        jTextField9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField9ActionPerformed(evt);
            }
        });
        jPanel9.add(jTextField9, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel9);

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel10.setLayout(new java.awt.BorderLayout());
        jPanel10.add(jTextField10, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel10);

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));
        jPanel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel11.setLayout(new java.awt.BorderLayout());
        jPanel11.add(jTextField11, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel11);

        jPanel12.setBackground(new java.awt.Color(255, 255, 255));
        jPanel12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel12.setLayout(new java.awt.BorderLayout());
        jPanel12.add(jTextField12, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel12);

        jPanel13.setBackground(new java.awt.Color(255, 255, 255));
        jPanel13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel13.setLayout(new java.awt.BorderLayout());
        jPanel13.add(jTextField13, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel13);

        jPanel14.setBackground(new java.awt.Color(255, 255, 255));
        jPanel14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel14.setLayout(new java.awt.BorderLayout());
        jPanel14.add(jTextField2, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel14);

        jPanel15.setBackground(new java.awt.Color(255, 255, 255));
        jPanel15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel15.setLayout(new java.awt.BorderLayout());
        jPanel15.add(jTextField3, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel15);

        jPanel16.setBackground(new java.awt.Color(255, 255, 255));
        jPanel16.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel16.setLayout(new java.awt.BorderLayout());
        jPanel16.add(jTextField14, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel16);

        jPanel17.setBackground(new java.awt.Color(255, 255, 255));
        jPanel17.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel17.setLayout(new java.awt.BorderLayout());

        jTextField15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField15ActionPerformed(evt);
            }
        });
        jPanel17.add(jTextField15, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel17);

        jPanel18.setBackground(new java.awt.Color(255, 255, 255));
        jPanel18.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel18.setLayout(new java.awt.BorderLayout());
        jPanel18.add(jTextField16, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel18);

        jPanel19.setBackground(new java.awt.Color(255, 255, 255));
        jPanel19.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel19.setLayout(new java.awt.BorderLayout());
        jPanel19.add(jTextField17, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel19);

        jPanel20.setBackground(new java.awt.Color(255, 255, 255));
        jPanel20.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel20.setLayout(new java.awt.BorderLayout());
        jPanel20.add(jTextField18, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel20);

        jPanel21.setBackground(new java.awt.Color(255, 255, 255));
        jPanel21.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel21.setLayout(new java.awt.BorderLayout());
        jPanel21.add(jTextField19, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel21);

        jPanel22.setBackground(new java.awt.Color(255, 255, 255));
        jPanel22.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel22.setLayout(new java.awt.BorderLayout());
        jPanel22.add(jTextField20, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel22);

        jPanel23.setBackground(new java.awt.Color(255, 255, 255));
        jPanel23.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel23.setLayout(new java.awt.BorderLayout());
        jPanel23.add(jTextField21, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel23);

        jPanel24.setBackground(new java.awt.Color(255, 255, 255));
        jPanel24.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel24.setLayout(new java.awt.BorderLayout());
        jPanel24.add(jTextField22, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel24);

        jPanel25.setBackground(new java.awt.Color(255, 255, 255));
        jPanel25.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel25.setLayout(new java.awt.BorderLayout());

        jTextField23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField23ActionPerformed(evt);
            }
        });
        jPanel25.add(jTextField23, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel25);

        jPanel26.setBackground(new java.awt.Color(255, 255, 255));
        jPanel26.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel26.setLayout(new java.awt.BorderLayout());

        jTextField24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField24ActionPerformed(evt);
            }
        });
        jPanel26.add(jTextField24, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel26);

        jPanel27.setBackground(new java.awt.Color(255, 255, 255));
        jPanel27.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel27.setLayout(new java.awt.BorderLayout());
        jPanel27.add(jTextField25, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel27);

        jPanel28.setBackground(new java.awt.Color(255, 255, 255));
        jPanel28.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel28.setLayout(new java.awt.BorderLayout());
        jPanel28.add(jTextField26, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel28);

        jPanel29.setBackground(new java.awt.Color(255, 255, 255));
        jPanel29.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel29.setLayout(new java.awt.BorderLayout());

        jTextField27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField27ActionPerformed(evt);
            }
        });
        jPanel29.add(jTextField27, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel29);

        jPanel30.setBackground(new java.awt.Color(255, 255, 255));
        jPanel30.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel30.setLayout(new java.awt.BorderLayout());
        jPanel30.add(jTextField36, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel30);

        jPanel31.setBackground(new java.awt.Color(255, 255, 255));
        jPanel31.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel31.setLayout(new java.awt.BorderLayout());
        jPanel31.add(jTextField28, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel31);

        jPanel32.setBackground(new java.awt.Color(255, 255, 255));
        jPanel32.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel32.setLayout(new java.awt.BorderLayout());

        jTextField29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField29ActionPerformed(evt);
            }
        });
        jPanel32.add(jTextField29, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel32);

        jPanel33.setBackground(new java.awt.Color(255, 255, 255));
        jPanel33.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel33.setLayout(new java.awt.BorderLayout());
        jPanel33.add(jTextField30, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel33);

        jPanel34.setBackground(new java.awt.Color(255, 255, 255));
        jPanel34.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel34.setLayout(new java.awt.BorderLayout());
        jPanel34.add(jTextField31, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel34);

        jPanel35.setBackground(new java.awt.Color(255, 255, 255));
        jPanel35.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel35.setLayout(new java.awt.BorderLayout());

        jTextField32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField32ActionPerformed(evt);
            }
        });
        jPanel35.add(jTextField32, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel35);

        jPanel36.setBackground(new java.awt.Color(255, 255, 255));
        jPanel36.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel36.setLayout(new java.awt.BorderLayout());
        jPanel36.add(jTextField33, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel36);

        jPanel37.setBackground(new java.awt.Color(255, 255, 255));
        jPanel37.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel37.setLayout(new java.awt.BorderLayout());

        jTextField34.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField34ActionPerformed(evt);
            }
        });
        jPanel37.add(jTextField34, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel37);

        jPanel38.setBackground(new java.awt.Color(255, 255, 255));
        jPanel38.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel38.setLayout(new java.awt.BorderLayout());

        jTextField35.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField35ActionPerformed(evt);
            }
        });
        jPanel38.add(jTextField35, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel38);

        jPanel39.setBackground(new java.awt.Color(255, 255, 255));
        jPanel39.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel39.setLayout(new java.awt.BorderLayout());
        jPanel39.add(jTextField37, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel39);

        jPanel40.setBackground(new java.awt.Color(255, 255, 255));
        jPanel40.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel40.setLayout(new java.awt.BorderLayout());
        jPanel40.add(jTextField38, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel40);

        jPanel41.setBackground(new java.awt.Color(255, 255, 255));
        jPanel41.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel41.setLayout(new java.awt.BorderLayout());

        jTextField39.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField39ActionPerformed(evt);
            }
        });
        jPanel41.add(jTextField39, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel41);

        jPanel42.setBackground(new java.awt.Color(255, 255, 255));
        jPanel42.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel42.setLayout(new java.awt.BorderLayout());
        jPanel42.add(jTextField40, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel42);

        jPanel43.setBackground(new java.awt.Color(255, 255, 255));
        jPanel43.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel43.setLayout(new java.awt.BorderLayout());
        jPanel43.add(jTextField41, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel43);

        jPanel44.setBackground(new java.awt.Color(255, 255, 255));
        jPanel44.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel44.setLayout(new java.awt.BorderLayout());

        jTextField42.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField42ActionPerformed(evt);
            }
        });
        jPanel44.add(jTextField42, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel44);

        jPanel45.setBackground(new java.awt.Color(255, 255, 255));
        jPanel45.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel45.setLayout(new java.awt.BorderLayout());
        jPanel45.add(jTextField43, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel45);

        jPanel46.setBackground(new java.awt.Color(255, 255, 255));
        jPanel46.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel46.setLayout(new java.awt.BorderLayout());
        jPanel46.add(jTextField44, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel46);

        jPanel47.setBackground(new java.awt.Color(255, 255, 255));
        jPanel47.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel47.setLayout(new java.awt.BorderLayout());
        jPanel47.add(jTextField45, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel47);

        jPanel48.setBackground(new java.awt.Color(255, 255, 255));
        jPanel48.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel48.setLayout(new java.awt.BorderLayout());
        jPanel48.add(jTextField46, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel48);

        jPanel49.setBackground(new java.awt.Color(255, 255, 255));
        jPanel49.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel49.setLayout(new java.awt.BorderLayout());

        jTextField47.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField47ActionPerformed(evt);
            }
        });
        jPanel49.add(jTextField47, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel49);

        jPanel50.setBackground(new java.awt.Color(255, 255, 255));
        jPanel50.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel50.setLayout(new java.awt.BorderLayout());

        jTextField48.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField48ActionPerformed(evt);
            }
        });
        jPanel50.add(jTextField48, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel50);

        jPanel51.setBackground(new java.awt.Color(255, 255, 255));
        jPanel51.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel51.setLayout(new java.awt.BorderLayout());

        jTextField49.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField49ActionPerformed(evt);
            }
        });
        jPanel51.add(jTextField49, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel51);

        jPanel52.setBackground(new java.awt.Color(255, 255, 255));
        jPanel52.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel52.setLayout(new java.awt.BorderLayout());

        jTextField50.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField50ActionPerformed(evt);
            }
        });
        jPanel52.add(jTextField50, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel52);

        jPanel53.setBackground(new java.awt.Color(255, 255, 255));
        jPanel53.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel53.setLayout(new java.awt.BorderLayout());
        jPanel53.add(jTextField51, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel53);

        jPanel54.setBackground(new java.awt.Color(255, 255, 255));
        jPanel54.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel54.setLayout(new java.awt.BorderLayout());
        jPanel54.add(jTextField54, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel54);

        jPanel55.setBackground(new java.awt.Color(255, 255, 255));
        jPanel55.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel55.setLayout(new java.awt.BorderLayout());
        jPanel55.add(jTextField52, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel55);

        jPanel56.setBackground(new java.awt.Color(255, 255, 255));
        jPanel56.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel56.setLayout(new java.awt.BorderLayout());
        jPanel56.add(jTextField53, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel56);

        jPanel57.setBackground(new java.awt.Color(255, 255, 255));
        jPanel57.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel57.setLayout(new java.awt.BorderLayout());

        jTextField55.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField55ActionPerformed(evt);
            }
        });
        jPanel57.add(jTextField55, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel57);

        jPanel58.setBackground(new java.awt.Color(255, 255, 255));
        jPanel58.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel58.setLayout(new java.awt.BorderLayout());
        jPanel58.add(jTextField56, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel58);

        jPanel59.setBackground(new java.awt.Color(255, 255, 255));
        jPanel59.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel59.setLayout(new java.awt.BorderLayout());
        jPanel59.add(jTextField57, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel59);

        jPanel60.setBackground(new java.awt.Color(255, 255, 255));
        jPanel60.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel60.setLayout(new java.awt.BorderLayout());

        jTextField58.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField58ActionPerformed(evt);
            }
        });
        jPanel60.add(jTextField58, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel60);

        jPanel61.setBackground(new java.awt.Color(255, 255, 255));
        jPanel61.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel61.setLayout(new java.awt.BorderLayout());

        jTextField59.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField59ActionPerformed(evt);
            }
        });
        jPanel61.add(jTextField59, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel61);

        jPanel62.setBackground(new java.awt.Color(255, 255, 255));
        jPanel62.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel62.setLayout(new java.awt.BorderLayout());

        jTextField60.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField60ActionPerformed(evt);
            }
        });
        jPanel62.add(jTextField60, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel62);

        jPanel63.setBackground(new java.awt.Color(255, 255, 255));
        jPanel63.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel63.setLayout(new java.awt.BorderLayout());
        jPanel63.add(jTextField61, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel63);

        jPanel64.setBackground(new java.awt.Color(255, 255, 255));
        jPanel64.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel64.setLayout(new java.awt.BorderLayout());
        jPanel64.add(jTextField62, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel64);

        jPanel65.setBackground(new java.awt.Color(255, 255, 255));
        jPanel65.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel65.setLayout(new java.awt.BorderLayout());

        jTextField63.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField63ActionPerformed(evt);
            }
        });
        jPanel65.add(jTextField63, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel65);

        jPanel66.setBackground(new java.awt.Color(255, 255, 255));
        jPanel66.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel66.setLayout(new java.awt.BorderLayout());

        jTextField64.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField64ActionPerformed(evt);
            }
        });
        jPanel66.add(jTextField64, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel66);

        jPanel67.setBackground(new java.awt.Color(255, 255, 255));
        jPanel67.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel67.setLayout(new java.awt.BorderLayout());
        jPanel67.add(jTextField65, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel67);

        jPanel68.setBackground(new java.awt.Color(255, 255, 255));
        jPanel68.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel68.setLayout(new java.awt.BorderLayout());

        jTextField66.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField66ActionPerformed(evt);
            }
        });
        jPanel68.add(jTextField66, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel68);

        jPanel69.setBackground(new java.awt.Color(255, 255, 255));
        jPanel69.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel69.setLayout(new java.awt.BorderLayout());

        jTextField67.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField67ActionPerformed(evt);
            }
        });
        jPanel69.add(jTextField67, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel69);

        jPanel70.setBackground(new java.awt.Color(255, 255, 255));
        jPanel70.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel70.setLayout(new java.awt.BorderLayout());

        jTextField68.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField68ActionPerformed(evt);
            }
        });
        jPanel70.add(jTextField68, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel70);

        jPanel71.setBackground(new java.awt.Color(255, 255, 255));
        jPanel71.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel71.setLayout(new java.awt.BorderLayout());
        jPanel71.add(jTextField69, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel71);

        jPanel72.setBackground(new java.awt.Color(255, 255, 255));
        jPanel72.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel72.setLayout(new java.awt.BorderLayout());

        jTextField70.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField70ActionPerformed(evt);
            }
        });
        jPanel72.add(jTextField70, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel72);

        jPanel73.setBackground(new java.awt.Color(255, 255, 255));
        jPanel73.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel73.setLayout(new java.awt.BorderLayout());
        jPanel73.add(jTextField71, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel73);

        jPanel74.setBackground(new java.awt.Color(255, 255, 255));
        jPanel74.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel74.setLayout(new java.awt.BorderLayout());
        jPanel74.add(jTextField72, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel74);

        jPanel75.setBackground(new java.awt.Color(255, 255, 255));
        jPanel75.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel75.setLayout(new java.awt.BorderLayout());
        jPanel75.add(jTextField73, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel75);

        jPanel76.setBackground(new java.awt.Color(255, 255, 255));
        jPanel76.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel76.setLayout(new java.awt.BorderLayout());
        jPanel76.add(jTextField74, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel76);

        jPanel77.setBackground(new java.awt.Color(255, 255, 255));
        jPanel77.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel77.setLayout(new java.awt.BorderLayout());
        jPanel77.add(jTextField75, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel77);

        jPanel78.setBackground(new java.awt.Color(255, 255, 255));
        jPanel78.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel78.setLayout(new java.awt.BorderLayout());
        jPanel78.add(jTextField76, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel78);

        jPanel79.setBackground(new java.awt.Color(255, 255, 255));
        jPanel79.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel79.setLayout(new java.awt.BorderLayout());

        jTextField77.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField77ActionPerformed(evt);
            }
        });
        jPanel79.add(jTextField77, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel79);

        jPanel80.setBackground(new java.awt.Color(255, 255, 255));
        jPanel80.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel80.setLayout(new java.awt.BorderLayout());
        jPanel80.add(jTextField78, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel80);

        jPanel81.setBackground(new java.awt.Color(255, 255, 255));
        jPanel81.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel81.setLayout(new java.awt.BorderLayout());
        jPanel81.add(jTextField79, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel81);

        jPanel82.setBackground(new java.awt.Color(255, 255, 255));
        jPanel82.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel82.setLayout(new java.awt.BorderLayout());
        jPanel82.add(jTextField80, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel82);

        jPanel83.setBackground(new java.awt.Color(255, 255, 255));
        jPanel83.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel83.setLayout(new java.awt.BorderLayout());

        jTextField81.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField81ActionPerformed(evt);
            }
        });
        jPanel83.add(jTextField81, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel83);

        jButton1.setText("HINT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("EXIT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("jButton3");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jTextField82.setText("jTextField82");
        jTextField82.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField82ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jButton3)))
                .addContainerGap(33, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jTextField82, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jTextField82, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75)
                .addComponent(jButton2)
                .addGap(56, 56, 56)
                .addComponent(jButton3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 473, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 403, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed

    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8ActionPerformed

    private void jTextField9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField9ActionPerformed

    private void jTextField15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField15ActionPerformed

    private void jTextField23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField23ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField23ActionPerformed

    private void jTextField24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField24ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField24ActionPerformed

    private void jTextField27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField27ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField27ActionPerformed

    private void jTextField29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField29ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField29ActionPerformed

    private void jTextField32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField32ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField32ActionPerformed

    private void jTextField34ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField34ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField34ActionPerformed

    private void jTextField35ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField35ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField35ActionPerformed

    private void jTextField39ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField39ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField39ActionPerformed

    private void jTextField42ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField42ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField42ActionPerformed

    private void jTextField47ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField47ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField47ActionPerformed

    private void jTextField48ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField48ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField48ActionPerformed

    private void jTextField49ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField49ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField49ActionPerformed

    private void jTextField50ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField50ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField50ActionPerformed

    private void jTextField55ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField55ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField55ActionPerformed

    private void jTextField58ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField58ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField58ActionPerformed

    private void jTextField59ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField59ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField59ActionPerformed

    private void jTextField60ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField60ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField60ActionPerformed

    private void jTextField63ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField63ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField63ActionPerformed

    private void jTextField64ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField64ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField64ActionPerformed

    private void jTextField66ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField66ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField66ActionPerformed

    private void jTextField67ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField67ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField67ActionPerformed

    private void jTextField68ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField68ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField68ActionPerformed

    private void jTextField70ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField70ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField70ActionPerformed

    private void jTextField77ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField77ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField77ActionPerformed

    private void jTextField81ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField81ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField81ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        System.exit(0);   // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       jTextField82.setText("hell");
       jTextField1.setText(Integer.toString(mat[0][0]));
      jTextField4.setText(Integer.toString(mat[0][1]));
     jTextField5.setText(Integer.toString(mat[0][2]));
        jTextField6.setText(Integer.toString(mat[0][3]));
        jTextField7.setText(Integer.toString(mat[0][4]));
        jTextField8.setText(Integer.toString(mat[0][5]));
        jTextField9.setText(Integer.toString(mat[0][6]));
        jTextField10.setText(Integer.toString(mat[0][7]));
        jTextField11.setText(Integer.toString(mat[0][8]));
        jTextField12.setText(Integer.toString(mat[1][0]));
        jTextField13.setText(Integer.toString(mat[1][1]));
        jTextField2.setText(Integer.toString(mat[1][2]));
        jTextField3.setText(Integer.toString(mat[1][3]));
        jTextField14.setText(Integer.toString(mat[1][4]));
        jTextField15.setText(Integer.toString(mat[1][5]));
        jTextField16.setText(Integer.toString(mat[1][6]));
        jTextField17.setText(Integer.toString(mat[1][7]));
        jTextField18.setText(Integer.toString(mat[1][8]));
        jTextField19.setText(Integer.toString(mat[2][0]));
        jTextField20.setText(Integer.toString(mat[2][1]));
        jTextField21.setText(Integer.toString(mat[2][2]));
        jTextField22.setText(Integer.toString(mat[2][3]));
        jTextField23.setText(Integer.toString(mat[2][4]));
        jTextField24.setText(Integer.toString(mat[2][5]));
        jTextField25.setText(Integer.toString(mat[2][6]));
        jTextField26.setText(Integer.toString(mat[2][7]));
        jTextField27.setText(Integer.toString(mat[2][8]));
        jTextField36.setText(Integer.toString(mat[3][0]));
        jTextField28.setText(Integer.toString(mat[3][1]));
        jTextField29.setText(Integer.toString(mat[3][2]));
        jTextField30.setText(Integer.toString(mat[3][3]));
        jTextField31.setText(Integer.toString(mat[3][4]));
        jTextField32.setText(Integer.toString(mat[3][5]));
        jTextField33.setText(Integer.toString(mat[3][6]));
        jTextField34.setText(Integer.toString(mat[3][7]));
        jTextField35.setText(Integer.toString(mat[3][8]));
        jTextField37.setText(Integer.toString(mat[4][0]));
        jTextField38.setText(Integer.toString(mat[4][1]));
        jTextField39.setText(Integer.toString(mat[4][2]));
        jTextField40.setText(Integer.toString(mat[4][3]));
        jTextField41.setText(Integer.toString(mat[4][4]));
        jTextField42.setText(Integer.toString(mat[4][5]));
        jTextField43.setText(Integer.toString(mat[4][6]));
        jTextField44.setText(Integer.toString(mat[4][7]));
        jTextField45.setText(Integer.toString(mat[4][8]));
        jTextField46.setText(Integer.toString(mat[5][0]));        
        jTextField47.setText(Integer.toString(mat[5][1]));
        jTextField48.setText(Integer.toString(mat[5][2]));
        jTextField49.setText(Integer.toString(mat[5][3]));
        jTextField50.setText(Integer.toString(mat[5][4]));
        jTextField51.setText(Integer.toString(mat[5][5]));
        jTextField54.setText(Integer.toString(mat[5][6]));
        jTextField52.setText(Integer.toString(mat[5][7]));
        jTextField53.setText(Integer.toString(mat[5][8]));
        jTextField55.setText(Integer.toString(mat[6][0]));
        jTextField56.setText(Integer.toString(mat[6][1]));
        jTextField57.setText(Integer.toString(mat[6][2]));
        jTextField58.setText(Integer.toString(mat[6][3]));
        jTextField59.setText(Integer.toString(mat[6][4]));
        jTextField60.setText(Integer.toString(mat[6][5]));
        jTextField61.setText(Integer.toString(mat[6][6]));
        jTextField62.setText(Integer.toString(mat[6][7]));
        jTextField63.setText(Integer.toString(mat[6][8]));
        jTextField64.setText(Integer.toString(mat[7][0]));
        jTextField65.setText(Integer.toString(mat[7][1]));
        jTextField66.setText(Integer.toString(mat[7][2]));
        jTextField67.setText(Integer.toString(mat[7][3]));
        jTextField68.setText(Integer.toString(mat[7][4]));
        jTextField69.setText(Integer.toString(mat[7][5]));
        jTextField70.setText(Integer.toString(mat[7][6]));
        jTextField71.setText(Integer.toString(mat[7][7]));
        jTextField72.setText(Integer.toString(mat[7][8]));
        jTextField73.setText(Integer.toString(mat[8][0]));
        jTextField74.setText(Integer.toString(mat[8][1]));
        jTextField75.setText(Integer.toString(mat[8][2]));
        jTextField76.setText(Integer.toString(mat[8][3]));
        jTextField77.setText(Integer.toString(mat[8][4]));
        jTextField78.setText(Integer.toString(mat[8][5]));
        jTextField79.setText(Integer.toString(mat[8][6]));
        jTextField80.setText(Integer.toString(mat[8][7]));
        jTextField81.setText(Integer.toString(mat[8][8]));
// TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextField82ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField82ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField82ActionPerformed

    /**
     * @param args the command line arguments
     */
     static int[] mat[]; 
    static int N; // number of columns/rows. 
    static int SRN; // square root of N 
          static  int K; // No. Of missing digits 
     
  
  
    // Constructor 
    S3(int N, int K) 
    { 
        S3.N = N; 
        S3.K = K; 
        Double SRNd = Math.sqrt(N); 
        SRN = SRNd.intValue(); 
        mat = new int[N][N]; 
    } 
     // Sudoku Generator 
    public static void fillValues() 
    { 
        // Fill the diagonal of SRN x SRN matrices 
        fillDiagonal(); 
        // Fill remaining blocks 
        fillRemaining(0, SRN); 
        // Remove Randomly K digits to make game 
        removeKDigits(); 
    } 
    static void fillDiagonal() 
    { 
  
        for (int i = 0; i<N; i=i+SRN) 
  
            // for diagonal box, start coordinates->i==j 
            fillBox(i, i); 
    } 
     // Returns false if given 3 x 3 block contains num. 
   static boolean unUsedInBox(int rowStart, int colStart, int num) 
    { 
        for (int i = 0; i<SRN; i++) 
            for (int j = 0; j<SRN; j++) 
                if (mat[rowStart+i][colStart+j]==num) 
                    return false; 
  
        return true; 
    } 
    // Fill a 3 x 3 matrix. 
    static void fillBox(int row,int col) 
    { 
        int num; 
        for (int i=0; i<SRN; i++) 
        { 
            for (int j=0; j<SRN; j++) 
            { 
                do
                { 
                    num = randomGenerator(N); 
                } 
                while (!unUsedInBox(row, col, num)); 
  
                mat[row+i][col+j] = num; 
            } 
        } 
    } 
    // Random generator 
   static int randomGenerator(int num) 
    { 
        return (int) Math.floor((Math.random()*num+1)); 
    } 
    // Check if safe to put in cell 
    static boolean CheckIfSafe(int i,int j,int num) 
    { 
        return (unUsedInRow(i, num) && 
                unUsedInCol(j, num) && 
                unUsedInBox(i-i%SRN, j-j%SRN, num)); 
    } 
    // check in the row for existence 
    static boolean unUsedInRow(int i,int num) 
    { 
        for (int j = 0; j<N; j++) 
           if (mat[i][j] == num) 
                return false; 
        return true; 
    } 
    // check in the row for existence 
    static boolean unUsedInCol(int j,int num) 
    { 
        for (int i = 0; i<N; i++) 
            if (mat[i][j] == num) 
                return false; 
        return true; 
    } 
     // A recursive function to fill remaining matrix
    static boolean fillRemaining(int i, int j) 
    { 
        //  System.out.println(i+" "+j); 
        if (j>=N && i<N-1) 
        { 
            i = i + 1; 
            j = 0; 
        } 
        if (i>=N && j>=N) 
            return true; 
  
        if (i < SRN) 
        { 
            if (j < SRN) 
                j = SRN; 
        } 
        else if (i < N-SRN) 
        { 
            if (j==(int)(i/SRN)*SRN) 
                j =  j + SRN; 
        } 
        else
        { 
            if (j == N-SRN) 
            { 
                i = i + 1; 
                j = 0; 
                if (i>=N) 
                    return true; 
            } 
        } 
        for (int num = 1; num<=N; num++) 
        { 
            if (CheckIfSafe(i, j, num)) 
            { 
                mat[i][j] = num; 
                if (fillRemaining(i, j+1)) 
                    return true; 
  
                mat[i][j] = 0; 
            } 
        } 
        return false; 
    } 
    // Remove the K no. of digits to complete game
    public static void removeKDigits() 
    { 
           int count; 
        count = K;
        while (count != 0) 
        { 
              int cellId = randomGenerator(N*N);
            // System.out.println(cellId); 
            // extract coordinates i  and j 
            int i = (cellId/N); 
            int j = cellId%9; 
            if (j != 0) 
                j = j - 1; 
            // System.out.println(i+" "+j); 
            if (mat[i][j] != 0) 
            { 
                count--; 
                mat[i][j] = 0; 
            } 
        } 
    } 
     // Print sudoku 

    /**
     *
     * @param x
     * @param y
     * @return
     */
    public  int getSudoku(int x,int y) 
    { 
       /* for (int i = 0; i<N; i++) 
        { 
            for (int j = 0; j<N; j++) 
                System.out.print(mat[i][j] + " "); 
            System.out.println(); 
        } 
        System.out.println();*/ 
        return mat[x][y];
    } 
    
    // sudoku solver
    
   private int[][] board;
	public static final int EMPTY = 0; // empty cell
	public static final int SIZE = 9; // size of our Sudoku grids
	
	public S3(int[][] board) {
		this.board = new int[SIZE][SIZE];
		
		for (int i = 0; i < SIZE; i++) {
			for (int j = 0; j < SIZE; j++) {
				this.board[i][j] = board[i][j];
			}
		}
	}
	
	// we check if a possible number is already in a row
	private boolean isInRow(int row, int number) {
		for (int i = 0; i < SIZE; i++)
			if (board[row][i] == number)
				return true;
		
		return false;
	}
	
	// we check if a possible number is already in a column
	private boolean isInCol(int col, int number) {
		for (int i = 0; i < SIZE; i++)
			if (board[i][col] == number)
				return true;
		
		return false;
	}
	
	// we check if a possible number is in its 3x3 box
	private boolean isInBox(int row, int col, int number) {
		int r = row - row % 3;
		int c = col - col % 3;
		
		for (int i = r; i < r + 3; i++)
			for (int j = c; j < c + 3; j++)
				if (board[i][j] == number)
					return true;
		
		return false;
	}
	
	// combined method to check if a number possible to a row,col position is ok
	private boolean isOk(int row, int col, int number) {
		return !isInRow(row, number)  &&  !isInCol(col, number)  &&  !isInBox(row, col, number);
	}
	
	// Solve method. We will use a recursive BackTracking algorithm.
       public boolean solve() {
        for (int row = 0; row < SIZE; row++) {
         for (int col = 0; col < SIZE; col++) {
          // we search an empty cell
          if (board[row][col] == EMPTY) {
            // we try possible numbers
            for (int number = 1; number <= SIZE; number++) {
              if (isOk(row, col, number)) {
                // number ok. it respects sudoku constraints
                board[row][col] = number;

                if (solve()) { // we start backtracking recursively
                  return true;
                } else { // if not a solution, we empty the cell and we continue
                  board[row][col] = EMPTY;
                }
             }
            }

            return false; // we return false
           }
          }
         }

         return true; // sudoku solved
	}
       public void display() {
		for (int i = 0; i < SIZE; i++) {
			for (int j = 0; j < SIZE; j++) {
				System.out.print(" " + board[i][j]);
			}
		
			System.out.println();
		}
		
		System.out.println();
	}

    
    
    
    
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(S3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(S3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(S3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(S3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

       
        
        int R=9,M=20;
        S3 ss;
        ss = new S3(R,M);
        S3.fillValues();
        
      
        
   
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new S3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JButton jButton1;
    private static javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    javax.swing.JPanel jPanel10;
    javax.swing.JPanel jPanel11;
    javax.swing.JPanel jPanel12;
    javax.swing.JPanel jPanel13;
    javax.swing.JPanel jPanel14;
    javax.swing.JPanel jPanel15;
    javax.swing.JPanel jPanel16;
    javax.swing.JPanel jPanel17;
    javax.swing.JPanel jPanel18;
    javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    javax.swing.JPanel jPanel20;
    javax.swing.JPanel jPanel21;
    javax.swing.JPanel jPanel22;
    javax.swing.JPanel jPanel23;
    javax.swing.JPanel jPanel24;
    javax.swing.JPanel jPanel25;
    javax.swing.JPanel jPanel26;
    javax.swing.JPanel jPanel27;
    javax.swing.JPanel jPanel28;
    javax.swing.JPanel jPanel29;
    javax.swing.JPanel jPanel3;
    javax.swing.JPanel jPanel30;
    javax.swing.JPanel jPanel31;
    javax.swing.JPanel jPanel32;
    javax.swing.JPanel jPanel33;
    javax.swing.JPanel jPanel34;
    javax.swing.JPanel jPanel35;
    javax.swing.JPanel jPanel36;
    javax.swing.JPanel jPanel37;
    javax.swing.JPanel jPanel38;
    javax.swing.JPanel jPanel39;
    javax.swing.JPanel jPanel4;
    javax.swing.JPanel jPanel40;
    javax.swing.JPanel jPanel41;
    javax.swing.JPanel jPanel42;
    javax.swing.JPanel jPanel43;
    javax.swing.JPanel jPanel44;
    javax.swing.JPanel jPanel45;
    javax.swing.JPanel jPanel46;
    javax.swing.JPanel jPanel47;
    javax.swing.JPanel jPanel48;
    javax.swing.JPanel jPanel49;
    javax.swing.JPanel jPanel5;
    javax.swing.JPanel jPanel50;
    javax.swing.JPanel jPanel51;
    javax.swing.JPanel jPanel52;
    javax.swing.JPanel jPanel53;
    javax.swing.JPanel jPanel54;
    javax.swing.JPanel jPanel55;
    javax.swing.JPanel jPanel56;
    javax.swing.JPanel jPanel57;
    javax.swing.JPanel jPanel58;
    javax.swing.JPanel jPanel59;
    javax.swing.JPanel jPanel6;
    javax.swing.JPanel jPanel60;
    javax.swing.JPanel jPanel61;
    javax.swing.JPanel jPanel62;
    javax.swing.JPanel jPanel63;
    javax.swing.JPanel jPanel64;
    javax.swing.JPanel jPanel65;
    javax.swing.JPanel jPanel66;
    javax.swing.JPanel jPanel67;
    javax.swing.JPanel jPanel68;
    javax.swing.JPanel jPanel69;
    javax.swing.JPanel jPanel7;
    javax.swing.JPanel jPanel70;
    javax.swing.JPanel jPanel71;
    javax.swing.JPanel jPanel72;
    javax.swing.JPanel jPanel73;
    javax.swing.JPanel jPanel74;
    javax.swing.JPanel jPanel75;
    javax.swing.JPanel jPanel76;
    javax.swing.JPanel jPanel77;
    javax.swing.JPanel jPanel78;
    javax.swing.JPanel jPanel79;
    javax.swing.JPanel jPanel8;
    javax.swing.JPanel jPanel80;
    javax.swing.JPanel jPanel81;
    javax.swing.JPanel jPanel82;
    javax.swing.JPanel jPanel83;
    javax.swing.JPanel jPanel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField19;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField20;
    private javax.swing.JTextField jTextField21;
    private javax.swing.JTextField jTextField22;
    private javax.swing.JTextField jTextField23;
    private javax.swing.JTextField jTextField24;
    private javax.swing.JTextField jTextField25;
    private javax.swing.JTextField jTextField26;
    private javax.swing.JTextField jTextField27;
    private javax.swing.JTextField jTextField28;
    private javax.swing.JTextField jTextField29;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField30;
    private javax.swing.JTextField jTextField31;
    private javax.swing.JTextField jTextField32;
    private javax.swing.JTextField jTextField33;
    private javax.swing.JTextField jTextField34;
    private javax.swing.JTextField jTextField35;
    private javax.swing.JTextField jTextField36;
    private javax.swing.JTextField jTextField37;
    private javax.swing.JTextField jTextField38;
    private javax.swing.JTextField jTextField39;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField40;
    private javax.swing.JTextField jTextField41;
    private javax.swing.JTextField jTextField42;
    private javax.swing.JTextField jTextField43;
    private javax.swing.JTextField jTextField44;
    private javax.swing.JTextField jTextField45;
    private javax.swing.JTextField jTextField46;
    private javax.swing.JTextField jTextField47;
    private javax.swing.JTextField jTextField48;
    private javax.swing.JTextField jTextField49;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField50;
    private javax.swing.JTextField jTextField51;
    private javax.swing.JTextField jTextField52;
    private javax.swing.JTextField jTextField53;
    private javax.swing.JTextField jTextField54;
    private javax.swing.JTextField jTextField55;
    private javax.swing.JTextField jTextField56;
    private javax.swing.JTextField jTextField57;
    private javax.swing.JTextField jTextField58;
    private javax.swing.JTextField jTextField59;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField60;
    private javax.swing.JTextField jTextField61;
    private javax.swing.JTextField jTextField62;
    private javax.swing.JTextField jTextField63;
    private javax.swing.JTextField jTextField64;
    private javax.swing.JTextField jTextField65;
    private javax.swing.JTextField jTextField66;
    private javax.swing.JTextField jTextField67;
    private javax.swing.JTextField jTextField68;
    private javax.swing.JTextField jTextField69;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField70;
    private javax.swing.JTextField jTextField71;
    private javax.swing.JTextField jTextField72;
    private javax.swing.JTextField jTextField73;
    private javax.swing.JTextField jTextField74;
    private javax.swing.JTextField jTextField75;
    private javax.swing.JTextField jTextField76;
    private javax.swing.JTextField jTextField77;
    private javax.swing.JTextField jTextField78;
    private javax.swing.JTextField jTextField79;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField80;
    private javax.swing.JTextField jTextField81;
    private javax.swing.JTextField jTextField82;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
